"""
Django settings for tutorialcadastro project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x@k(af4e#)l-p2+st795d1&f+xnqr#o67j7$i@6ev8mrw9$3dd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # django apps - add a/c
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites', # add a/c
    # 3rd party - Adicionado ao código
    'allauth', # add a/c
    'allauth.account', # add a/c
    'allauth.socialaccount', # add a/c
    'crispy_forms', # add a/c
    'anymail', # # add a/c (edição email)
    # local apps
    'pages.apps.PagesConfig', # add a/c
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tutorialcadastro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tutorialcadastro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# django-allauth

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1
LOGIN_REDIRECT_URL = "/" # Add a/c Local para redirecionar após login

ACCOUNT_SESSION_REMEMBER = True # Add a/c a opção "Lembrar - usuário/senha" ja fica definida pela página.

ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True # Add a/c Senha duas vezes ao cadastrar
ACCOUNT_USERNAME_REQUIRED = False # Add a/c
ACCOUNT_AUTHENTICATION_METHOD = "email" # Add a/c
ACCOUNT_EMAIL_REQUIRED = True # Add a/c
ACCOUNT_UNIQUE_EMAIL = True # Add a/c










# django-crispy-forms - Add a/c

CRISPY_TEMPLATE_PACK = "bootstrap4" # Add a/c

# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend" # Add a/c para cadastrar envio de email de confirmação NO CONSOLE

EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
DEFAULT_FROM_EMAIL = "no-reply@meusite.com.br"
SERVER_EMAIL = DEFAULT_FROM_EMAIL # repetiu a vaŕiável de cima que significa o mesmo e-mail.
ANYMAIL = {
    "MAILGUN_API_KEY" : "de9e5ce978b94abd1dd8de4de2844ac7-0be3b63b-7986ac30",
    "MAILGUN_SENDER_DOMAIN": "sandbox1095cdb6b056446191d439862ba55ef7.mailgun.org",
}